---
listen: 0.0.0.0:8080
redis:
  addr: 127.0.0.1:6379
  readtimeout: 50
  writetimeout: 50
  dialtimeout: 100
auth:
  hawk:
    root: toor
  apikey:
    testuser: test
  disableauth: false
violations:
  - name: test
    penalty: 50
    decreaselimit: 50
  - name: test2
    penalty: 5
    decreaselimit: 25
  - name: endpoint_abuse_violation
    penalty: 50
  - name: abusive_account_violation
    penalty: 100
  - name: hard_limit_violation
    penalty: 10
decay:
  points: 0
  interval: 1s
versionresponse: ./version.json
